### ISSUE TITLE
Update SkyMap on F-Droid

### ISSUE THREAD

**Issue by SecUpwN** [sky-map-team/stardroid#113]
Dear @sky-map-team, I love your app and wonder why you don't update your [app on F-Droid](https://f-droid.org/repository/browse/?&fdid=com.google.android.stardroid). The last update has been made in **2013**. Would you please update it? Thank you!

**Comment by jaydeetay** [comment]
Not really a bug report or feature request, so the wrong forum for this.

**Comment by SecUpwN** [comment]
>Not really a bug report or feature request, so the wrong forum for this.

Where to ask instead? And why not just give a proper answer?

**Comment by homersimpsons** [comment]
Up please

**Comment by SecUpwN** [comment]
>Up please

Seems like they don't care anymore.

**Comment by barbeau** [comment]
F-Droid inclusion policy is pretty strict:
https://f-droid.org/wiki/page/Inclusion_Policy

The app itself AND all libraries/dependencies must be open source.  Stardroid is using Google Play Services analytics and location, neither of which are open-source, so unfortunately it no longer meets the inclusion requirements.

IMHO, I'd like to see F-Droid relax their policies so more open-source apps that use closed source libraries can be included.  These days it's hard to build a good app, especially in the maps/location space, without using some closed source libraries.  I'd had a few open-source apps rejected from F-Droid due to the closed source libraries issue.

**Comment by homersimpsons** [comment]
For some apps that use third-party non-opensource code, F-Droid just display a message.

**Comment by barbeau** [comment]
@homersimpsons for which apps?

**Comment by homersimpsons** [comment]
@barbeau For [Osmand~](https://f-droid.org/repository/browse/?fdfilter=osmand&fdid=net.osmand.plus), [Face Slim](https://f-droid.org/repository/browse/?fdfilter=face+slim&fdid=org.indywidualni.fblite), [Forkhub](https://f-droid.org/repository/browse/?fdfilter=forkhub&fdid=jp.forkhub) and I'm sure there are other.

**Comment by barbeau** [comment]
@homersimpsons Thanks!  Interesting, looks like there is an anti features label for apps, including those with closed source dependencies:
https://f-droid.org/wiki/page/Antifeatures

It's admittedly been a while since the last app I submitted was rejected - maybe things have changed in the F-Droid submission process and those apps would now be allowed.

**Comment by jaydeetay** [comment]
skymapdevs@gmail.com would be a good place to discuss.
Cheers,
John

**Comment by homersimpsons** [comment]
Is there any news about F-Droid update?

**Comment by jaydeetay** [comment]
I haven't heard anything...I don't think the F-droid version was anything
to do with us.

**Comment by Poeticode** [comment]
It seems like there's been an update since this issue; but any chance of continuing the effort of keeping it up-to-date? F-Droid allegedly has the latest release (v1.9.2 on 2017-05-20), but I noticed the latest version on the Play Store is from 2018-09-06 with the What's New section including fixes found in commits beyond v1.9.2

Regardless, thank you all for opening the source! I know F-Droid is a pain.

**Comment by landry314** [comment]
the f-droid version is now 3 years old

**Comment by jaydeetay** [comment]
Sorry about that folks. The f-droid build broke a while back and I haven't
been able to devote the cycles to resurrect it.

**Comment by landry314** [comment]
1.9.6 - RC6 is not on F-Droid yet
