### ISSUE TITLE
Actual location of poles differ than what app shows.

### ISSUE THREAD

**Issue by heychirag** [sky-map-team/stardroid#167]
**Summary:** 

Technically, the angle between the poles can never be 180 (π radians) unless the app is being used on poles.

**Expected behavior:** 

The angle should be less than 180 (π radians). This means the app does not shows the precise location of objects below the horizon.

**Comment by ricknun** [comment]
Maybe I am not understanding, but the Summary and Expected Behavior don't seem correct.  It appears the post is saying that if the observer is on the earth equator for example, the observer is separated from a line connecting the north and south celestial poles by the radius of the earth, making the angle from north to south pole slightly less than 180 degrees.  But the poles aren't objects at a fixed distance from the earth -- they are points on the celestial sphere *at a distance of infinity*.  So the poles are exactly 180 degrees apart regardless of observer position on the earth.

**Comment by heychirag** [comment]
@ricknun Sorry for the wrong Summary and Expected. I hope the following picture makes my point rather clear.

![earth-png-27](https://user-images.githubusercontent.com/13611666/32403927-7af3d62c-c16b-11e7-97dd-0b849295cb75.png)

**Comment by ricknun** [comment]
I am saying there is no problem in Sky Map.  The north and south poles **of the earth** are not indicated in Sky Map.  The north and south poles **of the [celestial sphere](https://en.wikipedia.org/wiki/Celestial_sphere)** are indicated.  To an observer anywhere on earth, those two points are exactly pi radians apart.  In your diagram extending the earth's rotation axis infinitely North and South, then look at the ends (it doesn't end) of that line.
