### ISSUE TITLE
SkyMap license / Google PlayStore

### ISSUE THREAD

**Issue by pion3er** [sky-map-team/stardroid#171]
**Summary:** 

Am I allowed to upload my own modified version (with new name/package names) to the google PlayStore as this is under Apache2 license?

**Steps to reproduce:** 
Hi,
I recently uploaded a modified version of SkyMap to the Google PlayStore alpha testing section.
Google refused and blocked my app as it says that I'm violating the owner's rights of the stardroid app, although I changed the name of the app and the names of the packages. (com.google.*) I gave them a hint (a link) that the project is under Apache 2.0 license, but this did not change their opinion. To my understanding it should be possible to release my own modified version of Sky Map on the PlayStore (using another name) as of the Apache 2.0 license. Am I wrong?
Could you probably write some kind of authorization statement here as Google expects from me (see below)?

Thanks very much for your help!

Kind regards

Pion3er

Here's what Google wrote to me:

_______
Thanks for contacting the Google Play Team.

After further review, I'm not able to reinstate your app as it looks to be the same as an app that’s live on Google Play.

You can find the app here: https://play.google.com/store/apps/details?id=com.google.android.stardroid&e=-EnableAppDetailsPageRedesign

During my review, I wasn't able to confirm your app's relationship with the original content or brand owner(Sky Map Devs). 

In order for me to process your appeal, please reply with verifiable documentation that your app is authorized.

The documentation(PDF) needs to clearly indicate your ownership, or authorization. 

I won't be able to reinstate your app without documentation. I appreciate your assistance and look forward to your reply.

Regards...

**Expected behavior:** 

Being allowed on Google PlayStore due to Apache2.0 :)

**Observed behavior:** 

Not allowed :/

**Comment by jaydeetay** [comment]
Hi Pion3er,
That seems odd to me but IANAL and also haven't studied the Play Store's policies.  Also, as I work for Google as an engineer it puts me in a bit of a tricky spot as I don't want to be seen as in any way speaking for Google.  So, just speaking for me personally: there are other examples of Sky Map clones in the Play Store and elsewhere (I think "Indian Sky Map" is my favorite), so there's some precedent here.  (Again, my opinion only) I don't have a problem with SkyMap-derived code ending up in other apps (of course - hence the license), though if the app is very similar I'd certainly appreciate some effort being made to distinguish it (different name, different logo for example) so that it's not confused with Sky Map.  Do you think the Play Store's objection is less about the code than the 'branding'?  Could you satisfy them by changing the name and logo as I suggested?

**Comment by pion3er** [comment]
Hi, 
thanks again for the help here! Meanwhile they dropped the authorization issue. But it still got labeled as duplicate, also we renamed it, haven't used the SkyMap logo and made some obvious technical modifications. So I'm quite curious about what is exactly the reason for their decision.....

Kind regards 

pion3er

**Comment by jaydeetay** [comment]
Great! Sounds like the problem is solved then?  Good luck.

**Comment by jaydeetay** [comment]
Just to close this out (nearly 10 years later)... Sky Map has been somewhat plagued by copycat apps that make almost no change except stuffing the app full of ads.  Because of this we're shifting to new licensing for V2.  We're switching to GPLv3 which will make cloning the app less worthwhile and also keeping the look and feel of the app 'all rights reserved'.  No objection to the open source code being reused, as long as it's to create something new that has value.
