### ISSUE TITLE
Change date and Time opens twice in Time Travel on rapid click

### ISSUE THREAD

**Issue by shiv07tiwari** [sky-map-team/stardroid#237]
**Summary:** 

Options of time and date open twice when clicked rapidly.
**Steps to reproduce:** 

Time travel -> quickly click twice on change the date

**Comment by utkarsh530** [comment]
@shiv07tiwari can I work on this?

**Comment by jaydeetay** [comment]
It seems like there are currently multiple folks trying to solve this problem?  I certainly appreciate the efforts  people are making to improve Sky Map but how can we avoid folks wasting their time?

**Comment by makhanovable** [comment]
Sorry. It is my first experience in big open source project. Thats is why i  just opened issues list and started solve it one by one.

**Comment by shiv07tiwari** [comment]
@makhanovable You need to first ask the person who opened it.
@jaydeetay I will send a PR for this sson.

**Comment by jaydeetay** [comment]
Hi folks! You've probably seen me asking this on other threads, but just in case not, I'm curious - why the interest in Sky Map? All of a sudden I have quite a few people sending me PRs. It's nice that there's the interest, but I should say a few things (and I should put this in the README so that people see it)
1) Yes, I know that Sky Map's code and UX is very dated. It needs a big overhaul.
2) It still has a lot of users, so I have a responsibility to them that any changes we incorporate are properly considered.
3) I'm very short of time and I'm currently the main gatekeeper. So I'm really sorry if I'm slow to respond, but I do still need to be that gatekeeper.
4) Small, focussed PRs to fix bugs or upgrade dependencies etc are very easy for me to approve. If your PR does too much it might get stalled because even if 90% of it is welcome there might be 10% that I'm not happy with. So keep them small if you can. Plus, I'll be able to review them faster.
5) If you want to add a new *feature* then that's a bigger conversation. Please discuss with me first before writing a lot of code. 
6) Thanks for your contributions! I'm definitely appreciative even if my slowness to respond might make it seem otherwise.
