### ISSUE TITLE
Not all strings translated to russian

### ISSUE THREAD

**Issue by makhanovable** [sky-map-team/stardroid#261]
**Summary:** 

As a native russian speaker i can see that not all string translated to russian

**Steps to reproduce:** 

Edit device language to russian and open app

**Expected behavior:** 

All objects and settings strings should be translated

**Observed behavior:** 

Instead i see some english strings

**Device and Android version:** 

All

**Screenshots:** 

![Screenshot_2019-03-30-22-59-41-914_com google android stardroid](https://user-images.githubusercontent.com/28304184/55284952-b5b73180-53a2-11e9-9b63-5a4f3ee22899.png)

**Comment by jaydeetay** [comment]
Yes, I'm sorry about this.  The app was fully translated when it was owned by Google 10 years ago, but since  then as new features have been added we haven't had translator resources. So we generally rely on folks like yourself spotting the missing translations and advising us. If you have Russian translations for those missing phrases I'd gladly use them.

**Comment by makhanovable** [comment]
> 
> 
> Yes, I'm sorry about this. The app was fully translated when it was owned by Google 10 years ago, but since then as new features have been added we haven't had translator resources. So we generally rely on folks like yourself spotting the missing translations and advising us. If you have Russian translations for those missing phrases I'd gladly use them.

I will soon translate the missing phrases and create PR

**Comment by jaydeetay** [comment]
Thanks so much for doing this.
