### ISSUE TITLE
Size of sun is smaller than jupiter

### ISSUE THREAD

**Issue by bhushanon** [sky-map-team/stardroid#320]
**Summary:** 
28 Dec 2019 at 2.40 pm IST, Location :Mumbai

Size of sun is smaller than jupiter

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

**Steps to reproduce:** 

How can we reproduce the issue?

**Expected behavior:** 
The size of Jupiter should not be greater than Sun
![Screenshot_2019-12-28-14-43-59-792_com google android stardroid](https://user-images.githubusercontent.com/30391140/71541589-5d3cb100-2981-11ea-9cd1-724fb8854f86.jpg)

What did you expect the app to do?

**Observed behavior:** 

What did you see instead?  Describe your issue in detail here.

**Device and Android version:** 

What make and model device (e.g., Samsung Galaxy S7) did you encounter this on?  What Android version (e.g., Android 4.0 Ice Cream Sandwich) are you running?  Is it the stock version from the manufacturer or a custom ROM?  What version of Google Play Services is running on your device?

**Screenshots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by jaydeetay** [comment]
Yeah - that's not really a bug in that we aren't trying to show the solar system objects to scale (otherwise only the sun and moon would be anything more than a pixel!).  We made the sun and the moon roughly the same size so that eclipses would more or less work, but we don't have a policy on the rest of the objects.  We could perhaps put them in size order even if not to scale, but then do we order them by actual size or apparent size?

**Comment by bhushanon** [comment]
John
Thanks for reply.. in both actual and apparent size options, there will be display issues for sure 
so better it can be kept as it is
