### ISSUE TITLE
Unreasonable perspective changes when moving parallel

### ISSUE THREAD

**Issue by Adrianilloo** [sky-map-team/stardroid#330]
**Summary:** 

The Sky Map rendered view drastically shifts when moving the phone around while preserving its orientation, just as if you moved millions of kilometers away in the same direction. This is unreasonable, taking as an example that the Sun always appears parallel in the sky independently of our location, due to how far away it is from us.

**Steps to reproduce:** 

Open the application holding the phone properly in front of you, acknowledge the displayed view of the sky and then walk few meters around without rotating phone at all. Then, observe and compare the final sky view to the initial.

**Expected behavior:** 

Preserve the sky image identical across displacements (only when keeping the absolute same phone orientation). Ignoring significant angular changes across Earth along the position changes, naturally.

**Observed behavior:** 

The rendered image exaggeratedly shifts, displacing the relative positions of all objects (e.g. stars) from their initial screen coordinates. Also, image shifts in the same direction as the movement direction.

**Device and Android version:** 

- Model: Redmi 7
- Android version: Android 9 PKQ1.181021.001
- Custom ROM: MUI Global 11.0.7
- Google Play Services version: 20.24.14

**Screenshots:** 

Rendered view from initial position:

![Right](https://user-images.githubusercontent.com/15228896/88166159-22e57a80-cc17-11ea-8ea5-5100793d04f9.jpg)

Rendered view after moving about a meter to my left, without (practically) rotating the phone:

![Left](https://user-images.githubusercontent.com/15228896/88166175-27aa2e80-cc17-11ea-80fb-080ec8bab810.jpg)

I don't discard it may be an incompatibility with my phone, but I think sensors are fine. I didn't mess with any sensor configuration, and it's a new phone.

**Comment by jaydeetay** [comment]
I suspect what's happening here is that your compass is just becoming properly calibrated as you move around. Sky Map just depends on the values the sensors report after all.  If the phone is pointing in the same direction, the sensors should all be reading the same (assuming it's motionless) and Sky Map should show the same view. If Sky Map is not showing the same view it's because the sensors are reporting different values.  The movement you describe is likely just allowing the compass to adjust to the local environment (just as it does when you do the figure of 8 motion).

There's one caveat here - if you have a phone without a gyro and you've changed the sensor settings in the app to use Sky Map's old method that's just based on compass and accelerometer, there IS some damping code that has a time dependency to it. That is, if you move the phone around and return it to its previous orientation the sensor readings may take a while to settle back to where they were.  But out of the box we don't use that old code any more.

Thanks for reporting this - if you disagree with my hypothesis feel free to reopen and we can discuss further.
