### ISSUE TITLE
Red (night) mode turns up screen brightness

### ISSUE THREAD

**Issue by zekooooo** [sky-map-team/stardroid#515]
Sony Xperia 1V, Android 14, Sky Map 1.10.4 - RC1 (F-Droid version)

When I click the eye icon to enter the red sky charts mode (or when I start the app, doesn't matter), the screen becomes significantly brighter instead of minimum brightness. This always happens in red charts mode, I can't have the sky charts red without the brightness going up.

Not a biggie since my screen is OLED and this is red light, but still, it would be nice to have screen dimming as usual.

**Comment by jaydeetay** [comment]
This is an oldie from back in the day when phones didn't really handle screen dimming properly.  I don't see much need for the app to do it now....the phone's own screen brightness management is probably just fine (and as if you've noted...the 'dim' value used is actually pretty bright on most phones these days).

**Comment by jaydeetay** [comment]
I'm going to try something.  Since we first implemented this (from looking
at the Android source code!) it looks like they might have added a constant
that means "really really dim".  I'm going to add some options to use a)
that b) the phone's automatic setting or c) the original value.  If you're
interested I can add you to the 'alpha testers' group and you can see how
it works for you.  Just send your google account name to
***@***.*** and I'll add you.  Another option is just to join our
beta testers for the Google Play link.  I see you're using the
fdroid version though so these options might not appeal to you.

**Comment by jaydeetay** [comment]
Why thank you github for obfuscating our email address.  Well....if you head on over to the Play Store you can contact us from there (if you want).

**Comment by zekooooo** [comment]
Sorry, I nuked Google Services on my phone. If you can / want to push an alpha version to F-Droid I'll let you know how each option worked, I just checked that beta updates for Sky Map are enabled in my F-Droid.

Thanks for giving this thought. I have no idea if there are many F-Droid users on your app and I don't think Sonys are selling well so I'm really thankful you're hearing me out at all.

**Comment by VasilisKos** [comment]
> Sorry, I nuked Google Services on my phone. If you can / want to push an alpha version to F-Droid I'll let you know how each option worked, I just checked that beta updates for Sky Map are enabled in my F-Droid.
> 
> Thanks for giving this thought. I have no idea if there are many F-Droid users on your app and I don't think Sonys are selling well so I'm really thankful you're hearing me out at all.

The issue is not only on Sony's. I can confirm that on my Nokia X20, with stock Android 14.

**Comment by jaydeetay** [comment]
Looking at the code we basically determined (in 2009!) a hard-coded
brightness value that worked on the phones we had at the time. If we went
any lower it turned the screen off entirely on some of the phones!  But
that value is clearly too bright for today's phones.
