### ISSUE TITLE
Auto mode stopped working on Moto E, since the March 8 update

### ISSUE THREAD

**Issue by mkarajohn** [sky-map-team/stardroid#68]
## Device

* [Motorola Moto E 2nd gen 4G](http://www.gsmarena.com/motorola_moto_e_(2nd_gen)-6986.php)

## OS

Android 5.0.2

## Issue description

After today's update the Auto Mode of the application stopped working. On startup an error message appears, informing me that my device is lacking one of the 2 necessary sensors, and when I enter the app I can only use it in Manual Mode.

## Expected behaviour

Up until now I was able to use both offered Modes on my device, so I would expect that I would still be able to use Auto Mode.

**Comment by mkarajohn** [comment]
Maybe [this](https://github.com/sky-map-team/stardroid/issues/19) issue has some merit, not sure. Linking it anyway.

**Comment by jaydeetay** [comment]
Great bug report.
Looks like the Moto E is described as lacking a compass.  It reports in the SensorManager it lacks a compass.  And yet if you register for magnetic sensor events you get them...so presumably Motorola used the same chipset as on their higher end phones but tried to differentiate by disabling the compass on the E - line (not entirely successfully).  That's the only explanation I can think of.  From the reviews we get from Moto E owners it seems that the compass isn't working on at least some.  Yet judging by the other 5 star reviews Dimitris isn't alone in having a working compass.  Weird.

The fix is clear - leave the warning in, but don't stop people using automode if it does actually work for them.

**Comment by jaydeetay** [comment]
Fixed in 1.8.2
